global:
  scrape_interval: '10s'
  scrape_timeout: '5s'

scrape_configs:
  - job_name: 'scraperoo'
    static_configs:
      - targets: ['scraperoo:3001']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:8070']
  - job_name: 'minio-job'
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: [ 'minio' ]
  - job_name: 'meilisearch'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: [ 'meilisearch' ]
  - job_name: 'scylla'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['scylla:9180']